---

- name: create glance endpoint
  keystone_service: >
    insecure=yes
    name="glance"
    type="image"
    description="Glance Image Service"
    publicurl="https://{{ keystone_external_ip }}:10000"
    internalurl="https://{{ keystone_internal_ip }}:10000"
    adminurl="https://{{ keystone_internal_ip }}:10000"
    region={{ keystone_region }}
    token={{ keystone_admin_token }}
    endpoint="https://{{ keystone_internal_ip }}:35357/v2.0"
