---

#
# Keystone endpoints
#

- name: create keystone identity point
  keystone_service: >
    insecure=yes
    name="keystone"
    type="identity"
    description="Keystone Identity Service"
    publicurl="https://{{ keystone_external_ip }}:5000/v2.0"
    internalurl="https://{{ keystone_internal_ip }}:5000/v2.0"
    adminurl="https://{{ keystone_internal_ip }}:35357/v2.0"
    region={{ keystone_region }}
    token={{ keystone_admin_token }}
    endpoint="https://{{ keystone_internal_ip }}:35357/v2.0"

- name: create EC2 compatability keystone service
  keystone_service: >
    insecure=yes
    name=ec2
    type=ec2
    description="EC2 Compatability Layer"
    publicurl=https://{{ keystone_external_ip }}:10004/services/Cloud
    internalurl=http://{{ keystone_internal_ip }}:10004/services/Cloud
    adminurl=http://{{ keystone_internal_ip }}:10004/services/Admin
    region={{ keystone_region }}
    token={{ keystone_admin_token }}
    endpoint="https://{{ keystone_internal_ip }}:35357/v2.0"
