
- name: install nova.conf file from template
  template: >
    src=roles/controller-common/templates/nova.conf.j2
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0644
  register: nova_conf

- name: install nova's api-paste.ini file from template
  template: >
    src=roles/controller-common/templates/nova-api-paste.ini.j2
    dest=/etc/nova/api-paste.ini
    owner=nova
    group=nova
    mode=0644
  register: nova_api_conf

# FIXME: not sure about all these services...
- name: restart nova services
  service: >
    name={{ item }}
    state=restarted
  with_items: nova_controller_services

  when: nova_conf.changed or nova_api_conf.changed

# FIXME: not sure about all these services...
- name: ensure nova services are running
  service: >
    name={{ item }}
    state=running
  with_items: nova_controller_services

# FIXME: wait for ports?
- name: pause for nova services
  pause: seconds=5
  when: nova_conf.changed or nova_api_conf.changed
