- name: create nova database
  mysql_db: >
    name=nova
    state=present
  register: nova_db

- name: create nova mysql user
  mysql_user: >
    name=nova
    password={{ nova_mysql_password }}
    host="%"
    priv=nova.*:ALL
    state=present

- name: sync nova database
  nova_manage: action=dbsync
  when: nova_db.changed

# FIXME: not sure about all these services...
- name: restart nova services
  service: >
    name={{ item }}
    state=restarted
  with_items:
    - nova-api
    - nova-cert
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
#    - nova-console
  when: nova_db.changed

# FIXME: not sure about all these services...
- name: ensure nova services are running
  service: >
    name={{ item }}
    state=running
  with_items:
    - nova-api
    - nova-cert
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
#    - nova-console

# FIXME: wait for ports?
- name: pause for nova services
  pause: seconds=5
  when: nova_db.changed


- name: ensure nova sqlite is deleted
  file: >
    dest=/var/lib/nova/nova.sqlite
    state=absent
