---

- name: create nova endpoint
  keystone_service: >
    insecure=yes
    name="nova"
    type="compute"
    description="OpenStack Compute"
    publicurl="https://{{ keystone_external_ip }}:10002/v2/%(tenant_id)s"
    internalurl="https://{{ keystone_internal_ip }}:10002/v2/%(tenant_id)s"
    adminurl="https://{{ keystone_internal_ip }}:10002/v2/%(tenant_id)s"
    region={{ keystone_region }}
    token={{ keystone_admin_token }}
    endpoint="https://{{ keystone_internal_ip }}:35357/v2.0"
