---

- name: create keystone database
  mysql_db: >
    name=keystone
    state=present
  register: keystone

- name: create keystone mysql user
  mysql_user: >
    name=keystone
    password={{ keystone_mysql_password }}
    priv=keystone.*:ALL
    state=present

- name: sync keystone database
  #command: keystone-manage db_sync
  keystone_manage: action=dbsync
  when: keystone.changed

- name: restart keystone
  service: >
    name=keystone
    state=restarted
  when: keystone.changed

- name: ensure keystone keystone is running
  service: >
    name=keystone
    state=running

- name: ensure keystone sqlite is deleted
  file: >
    dest=/var/lib/keystone/keystone.sqlite
    state=absent
