---

- name: copy over my.cnf from template
  template: >
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root
    group=root
    mode=0644
  register: mysql_conf

- name: restart mysql-server
  service: >
    name=mysql
    state=restarted
  when: mysql_conf.changed
