---

packages:
  - keystone
  - python-keyring
  - mysql-server
  - python-mysqldb
  - rabbitmq-server
  - glance
  - python-glanceclient
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - python-novaclient
