---

- hosts: all
  roles:
    - common

- hosts: controller-common
  roles:
    - controller-common

- hosts: controller-primary
  roles:
    - controller-primary

- hosts: compute
  roles:
    - compute
