---

- hosts: all
  roles:
    - common
  tasks:
    # Just less typing...
    - set_fact: keystone_external_ip={{ hostvars['controller01']['ansible_eth1']['ipv4']['address'] }}
    - set_fact: keystone_internal_ip={{ hostvars['controller01']['ansible_eth2']['ipv4']['address'] }}

- hosts: controller
  roles:
    - controller

- hosts: compute
  roles:
    - compute
