---

- name: install keystone.conf file from template
  template: >
    src=keystone.conf.j2
    dest=/etc/keystone/keystone.conf
    owner=root
    group=root
    mode=0644
  register: keystone_conf

- name: restart keystone
  service: >
    name=keystone
    state=restarted
  when: keystone_conf.changed
