---

- name: ensure required packages are installed
  apt: >
    name={{ item }}
    state=installed
    update_cache=yes
    cache_valid_time=3600
  with_items: packages

- include: keystone/main.yml
- include: glance/main.yml
- include: nova/main.yml

- name: install adminrc file
  template: >
    src=adminrc.j2
    dest=/home/vagrant/adminrc
    owner=vagrant
    group=vagrant
    mode=0640
