---

- name: ensure required packages are installed
  apt: >
    name={{ item }}
    state=installed
    update_cache=yes
    cache_valid_time=3600
  with_items: packages

- include: keystone/main.yml
- include: glance/main.yml
