---

- name: ensure required packages are installed
  apt: >
    name={{ item }}
    state=installed
    update_cache=yes
    cache_valid_time=3600
  with_items: packages

# OpenStack rc files
- include: rc-files.yml

- include: rabbitmq/main.yml

- include: haproxy/main.yml

- include: mysql-server.yml

- include: keystone/configure.yml
- include: keystone/db.yml
- include: keystone/endpoint.yml
- include: keystone/tenants.yml
- include: keystone/test.yml

- include: glance/configure.yml
- include: glance/endpoint.yml
- include: glance/db.yml
- include: glance/user.yml

- include: nova/configure.yml
- include: nova/endpoint.yml
- include: nova/db.yml
- include: nova/user.yml
