---

- name: install rsyslog configuration
  template: >
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644
  register: rsyslog_conf

- name: restart rsyslog when configuration changes
  service: >
    name=rsyslog
    state=restarted
  when: rsyslog_conf.changed
