
- name: ensure required packages are installed
  apt: name={{ item }} state=installed
  with_items: packages

- name: install nova.conf file from template
  template: >
    src=nova.conf.j2
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0644
  register: nova_conf

# FIXME: not sure about all these services...
- name: restart nova services
  service: >
    name={{ item }}
    state=restarted
  when: nova_conf.changed
  with_items:
    - nova-compute

# FIXME: not sure about all these services...
- name: ensure nova services are running
  service: >
    name={{ item }}
    state=running
  with_items:
    - nova-compute
  when: nova_conf.changed

# FIXME: wait for ports?
- name: pause for nova services
  pause: seconds=5
  when: nova_conf.changed
