---

- name: create keystone database
  mysql_db: >
    name=keystone
    state=present
  register: keystone_db

- name: create keystone mysql user
  mysql_user: >
    name=keystone
    host="%"
    password={{ keystone_mysql_password }}
    priv=keystone.*:ALL
    state=present

- name: sync keystone database
  #command: keystone-manage db_sync
  keystone_manage: action=dbsync
  when: keystone_db.changed

- name: restart keystone
  service: >
    name=keystone
    state=restarted
  when: keystone_db.changed

# FIXME: wait for port
- name: pause for keystone to come up
  pause: seconds=5
  when: keystone_db.changed

- name: ensure keystone is running
  service: >
    name=keystone
    state=running
    enabled=yes

- name: ensure keystone sqlite is deleted
  file: >
    dest=/var/lib/keystone/keystone.sqlite
    state=absent
