---

#
# Keystone endpoints
#

- name: create keystone identity point
  keystone_service: >
    insecure=yes
    name="keystone"
    type="identity"
    description="Keystone Identity Service"
    publicurl="https://{{ keystone_external_ip }}:5000/v2.0"
    internalurl="https://{{ keystone_internal_ip }}:5000/v2.0"
    adminurl="https://{{ keystone_internal_ip }}:35357/v2.0"
    region={{ keystone_region }}
    token={{ keystone_admin_token }}
    endpoint="https://{{ keystone_internal_ip }}:35357/v2.0"
